from src.constants import TRAINING, EVALUATING, HUMAN_VS_HUMAN, HUMAN_VS_AI, AI_VS_AI
from src.ai_settings import FULL_EXPLORATION_RATE_MODEL, SMALL_EXPLORATION_RATE_MODEL, NO_EXPLORATION_RATE_MODEL,\
    CONSTANT_EXPLORATION_RATE_MODEL

SESSION_TYPE = EVALUATING
PLAYERS = HUMAN_VS_HUMAN

NUMBER_OF_GAMES = 5

EXPLORATION_RATE_MODEL = NO_EXPLORATION_RATE_MODEL
