from src.constants import TRAINING, EVALUATING, HUMAN_VS_HUMAN, HUMAN_VS_AI, AI_VS_AI
from src.ai_settings import FULL_EXPLORATION_RATE_MODEL, SMALL_EXPLORATION_RATE_MODEL, NO_EXPLORATION_RATE_MODEL,\
    CONSTANT_EXPLORATION_RATE_MODEL

SESSION_TYPE = TRAINING
PLAYERS = AI_VS_AI

NUMBER_OF_GAMES = 500
SAVE_EVERY = 100
LOAD_AI = 500

DATA_DIR = "data"
AI_DIR = "ai"

EXPLORATION_RATE_MODEL = FULL_EXPLORATION_RATE_MODEL
